class GameAssets {
   static const Map<int, Map<String, dynamic>> MOVE_DATA = {
    5: {
      "name": "경계 태세",
      "power": 0,
      "accuracy": 100,
      "type": "normal",
      "category": "status",
      "unlock_level": 5,
      "pet_type": "dog", // [New]
      "description": "자세를 낮추고 경계하여 회피율을 높인다.",
      "effect": {"type": "stat_change", "stat": "evasion", "value": 2, "target": "self"},
      "effect_chance": 100,
      "max_pp": 20,
    },
    10: {
      "name": "위협의 포효",
      "power": 0,
      "accuracy": 100,
      "type": "normal",
      "category": "status",
      "unlock_level": 8,
      "pet_type": "dog",
      "description": "거칠게 포효하여 상대의 기를 꺽어 공격력을 낮춘다.",
      "effect": {"type": "stat_change", "stat": "strength", "value": -1, "target": "enemy"},
      "effect_chance": 100,
      "max_pp": 20,
    },
    15: {
      "name": "사냥 개시",
      "power": 60,
      "accuracy": 100,
      "type": "normal",
      "category": "physical",
      "unlock_level": 12,
      "pet_type": "dog",
      "priority": 2,
      "description": "누구보다 빠르게 먼저 공격한다. 사냥의 시작을 알린다.",
      "effect": null,
      "effect_chance": 0,
      "max_pp": 15,
    },
    25: {
      "name": "출혈 이빨",
      "power": 50,
      "accuracy": 95,
      "type": "normal",
      "category": "physical",
      "unlock_level": 18,
      "pet_type": "dog",
      "description": "상대를 물어뜯어 출혈을 일으킨다.",
      "effect": {"type": "status", "status": "bleed", "target": "enemy"},
      "effect_chance": 100,
      "max_pp": 15,
    },
    30: {
      "name": "야성 폭주",
      "power": 0,
      "accuracy": 100,
      "type": "normal",
      "category": "status",
      "unlock_level": 25,
      "pet_type": "dog",
      "description": "야성을 폭발시켜 방어를 포기하고 공격력을 대폭 올린다.",
      "effect": [
        {"type": "stat_change", "stat": "strength", "value": 3, "target": "self"},
        {"type": "stat_change", "stat": "defense", "value": -2, "target": "self"}
      ],
      "effect_chance": 100,
      "max_pp": 5,
    },
    45: {
      "name": "전투 감각",
      "power": 0,
      "accuracy": 100,
      "type": "psychic",
      "category": "status",
      "unlock_level": 35,
      "pet_type": "shared",
      "description": "전투 흐름을 읽어 명중률과 치명타율을 높인다.",
      "effect": [
        {"type": "stat_change", "stat": "accuracy", "value": 1, "target": "self"},
        {"type": "stat_change", "stat": "crit_rate", "value": 1, "target": "self"}
      ],
      "effect_chance": 100,
      "max_pp": 10,
    },
    50: {
      "name": "본능 각성",
      "power": 70,
      "accuracy": 100,
      "type": "fighting",
      "category": "physical",
      "unlock_level": 45,
      "pet_type": "shared",
      "scaling": "hp_loss",
      "description": "위기에 몰릴수록 더 강력한 힘을 발휘한다.",
      "effect": null,
      "effect_chance": 0,
      "max_pp": 5,
    },
    65: {
      "name": "집중",
      "power": 0,
      "accuracy": 100,
      "type": "normal",
      "category": "status",
      "unlock_level": 55,
      "pet_type": "shared",
      "description": "정신을 집중하여 급소를 노릴 확률을 높인다.",
      "effect": {"type": "stat_change", "stat": "crit_rate", "value": 2, "target": "self"},
      "effect_chance": 100,
      "max_pp": 15,
    },
    75: {
      "name": "지배의 포효",
      "power": 0,
      "accuracy": 90,
      "type": "dark",
      "category": "status",
      "unlock_level": 65,
      "pet_type": "shared",
      "description": "압도적인 존재감으로 상대를 공포에 질리게 한다.",
      "effect": {"type": "status", "status": "fear", "target": "enemy"},
      "effect_chance": 100,
      "max_pp": 5,
    },
    90: {
      "name": "전투의 정점",
      "power": 0,
      "accuracy": 100,
      "type": "normal",
      "category": "status",
      "unlock_level": 80,
      "pet_type": "shared",
      "description": "수많은 전투 경험으로 모든 능력을 끌어올린다.",
      "effect": [
        {"type": "stat_change", "stat": "strength", "value": 1, "target": "self"},
        {"type": "stat_change", "stat": "defense", "value": 1, "target": "self"},
        {"type": "stat_change", "stat": "agility", "value": 1, "target": "self"},
        {"type": "stat_change", "stat": "intelligence", "value": 1, "target": "self"}
      ],
      "effect_chance": 100,
      "max_pp": 5,
    },
    100: {
      "name": "야수의 왕",
      "power": 150,
      "accuracy": 100,
      "type": "dragon",
      "category": "physical",
      "unlock_level": 95,
      "pet_type": "shared",
      "description": "짐승의 왕으로서 모든 것을 짓밟는다.",
      "effect": [
        {"type": "stat_change", "stat": "strength", "value": 2, "target": "self"},
        {"type": "stat_change", "stat": "defense", "value": -2, "target": "enemy"}
      ],
      "effect_chance": 100,
      "max_pp": 1,
    },
    // --- 고양이 계열 (Cat) ---
    105: {
      "name": "그루밍",
      "power": 0,
      "accuracy": 100,
      "type": "normal",
      "category": "status",
      "unlock_level": 5,
      "pet_type": "cat",
      "description": "털을 고르며 마음을 진정시킨다. (회복 + 상태이상 제거)",
      "effect": {"type": "heal", "value": 20, "target": "self"},
      "effect_chance": 100,
      "max_pp": 15,
    },
    110: {
      "name": "냥냥 펀치",
      "power": 40,
      "accuracy": 100,
      "type": "normal",
      "category": "physical",
      "unlock_level": 8,
      "pet_type": "cat",
      "priority": 1,
      "description": "빠르게 앞발로 때린다. 선공 확률이 있다.",
      "effect": null,
      "effect_chance": 0,
      "max_pp": 25,
    },
    115: {
      "name": "살금살금",
      "power": 0,
      "accuracy": 100,
      "type": "dark",
      "category": "status",
      "unlock_level": 12,
      "pet_type": "cat",
      "description": "기척을 숨겨 회피율을 크게 높인다.",
      "effect": {"type": "stat_change", "stat": "evasion", "value": 2, "target": "self"},
      "effect_chance": 100,
      "max_pp": 10,
    },
    125: {
      "name": "할퀴기",
      "power": 55,
      "accuracy": 95,
      "type": "normal",
      "category": "physical",
      "unlock_level": 18,
      "pet_type": "cat",
      "description": "날카로운 발톱으로 할퀸다. (출혈 확률)",
      "effect": {"type": "status", "status": "bleed", "target": "enemy"},
      "effect_chance": 50,
      "max_pp": 15,
    },
    130: {
      "name": "야옹이의 분노",
      "power": 90,
      "accuracy": 90,
      "type": "dark",
      "category": "physical",
      "unlock_level": 25,
      "pet_type": "cat",
      "description": "화난 고양이의 무서움을 보여준다. 치명타 확률이 높다.",
      "effect": {"type": "stat_change", "stat": "crit_rate", "value": 2, "target": "self"},
      "effect_chance": 100,
      "max_pp": 5,
    },
    // --- 새 계열 (Bird) ---
    205: {
      "name": "쪼기",
      "power": 40,
      "accuracy": 100,
      "type": "flying",
      "category": "physical",
      "unlock_level": 5,
      "pet_type": "bird",
      "description": "부리로 콕콕 쪼아 공격한다.",
      "effect": null,
      "effect_chance": 0,
      "max_pp": 35,
    },
    210: {
      "name": "날개치기",
      "power": 0,
      "accuracy": 95,
      "type": "flying",
      "category": "status",
      "unlock_level": 8,
      "pet_type": "bird",
      "description": "날개를 퍼덕여 모래바람을 일으켜 상대 명중률을 낮춘다.",
      "effect": {"type": "stat_change", "stat": "accuracy", "value": -1, "target": "enemy"},
      "effect_chance": 100,
      "max_pp": 20,
    },
    215: {
      "name": "순풍",
      "power": 0,
      "accuracy": 100,
      "type": "flying",
      "category": "status",
      "unlock_level": 12,
      "pet_type": "bird",
      "description": "바람을 타고 속도를 높인다.",
      "effect": {"type": "stat_change", "stat": "agility", "value": 2, "target": "self"},
      "effect_chance": 100,
      "max_pp": 15,
    },
    225: {
      "name": "공중제비",
      "power": 60,
      "accuracy": 100,
      "type": "flying",
      "category": "physical",
      "unlock_level": 18,
      "pet_type": "bird",
      "description": "빠르게 공중을 돌아 상대의 허를 찌른다. (반드시 명중)",
      "effect": null,
      "effect_chance": 0,
      "max_pp": 20,
    },
    230: {
      "name": "폭풍우",
      "power": 110,
      "accuracy": 70,
      "type": "flying",
      "category": "special",
      "unlock_level": 25,
      "pet_type": "bird",
      "description": "거대한 폭풍을 일으킨다. 명중률은 낮지만 강력하다.",
      "effect": {"type": "status", "status": "confusion", "target": "enemy"},
      "effect_chance": 30,
      "max_pp": 5,
    }
  };
}