class GameAssets {
  static const Map<int, Map<String, dynamic>> MOVE_DATA = {
    5: {
      "name": "경계 태세",
      "power": 0,
      "accuracy": 100,
      "type": "normal",
      "category": "status",
      "description": "자세를 낮추고 경계하여 회피율을 높인다.",
      "effect": {"type": "stat_change", "stat": "evasion", "value": 2, "target": "self"},
      "effect_chance": 100,
      "max_pp": 20,
    },
    10: {
      "name": "위협의 포효",
      "power": 0,
      "accuracy": 100,
      "type": "normal", // Dart 주석은 // 를 사용합니다.
      "category": "status",
      "description": "거칠게 포효하여 상대의 기를 꺽어 공격력을 낮춘다.",
      "effect": {"type": "stat_change", "stat": "strength", "value": -1, "target": "enemy"},
      "effect_chance": 100,
      "max_pp": 20,
    },
    15: {
      "name": "사냥 개시",
      "power": 60,
      "accuracy": 100,
      "type": "normal",
      "category": "physical",
      "priority": 2,
      "description": "누구보다 빠르게 먼저 공격한다. 사냥의 시작을 알린다.",
      "effect": null, // Python의 None은 Dart에서 null입니다.
      "effect_chance": 0,
      "max_pp": 15,
    },
    25: {
      "name": "출혈 이빨",
      "power": 50,
      "accuracy": 95,
      "type": "normal",
      "category": "physical",
      "description": "상대를 물어뜯어 출혈을 일으킨다.",
      "effect": {"type": "status", "status": "bleed", "target": "enemy"},
      "effect_chance": 100,
      "max_pp": 15,
    },
    30: {
      "name": "야성 폭주",
      "power": 0,
      "accuracy": 100,
      "type": "normal",
      "category": "status",
      "description": "야성을 폭발시켜 방어를 포기하고 공격력을 대폭 올린다.",
      "effect": [
        {"type": "stat_change", "stat": "strength", "value": 3, "target": "self"},
        {"type": "stat_change", "stat": "defense", "value": -2, "target": "self"}
      ],
      "effect_chance": 100,
      "max_pp": 5,
    },
    45: {
      "name": "전투 감각",
      "power": 0,
      "accuracy": 100,
      "type": "psychic",
      "category": "status",
      "description": "전투 흐름을 읽어 명중률과 치명타율을 높인다.",
      "effect": [
        {"type": "stat_change", "stat": "accuracy", "value": 1, "target": "self"},
        {"type": "stat_change", "stat": "crit_rate", "value": 1, "target": "self"}
      ],
      "effect_chance": 100,
      "max_pp": 10,
    },
    50: {
      "name": "본능 각성",
      "power": 70,
      "accuracy": 100,
      "type": "fighting",
      "category": "physical",
      "scaling": "hp_loss",
      "description": "위기에 몰릴수록 더 강력한 힘을 발휘한다.",
      "effect": null,
      "effect_chance": 0,
      "max_pp": 5,
    },
    65: {
      "name": "집중",
      "power": 0,
      "accuracy": 100,
      "type": "normal",
      "category": "status",
      "description": "정신을 집중하여 급소를 노릴 확률을 높인다.",
      "effect": {"type": "stat_change", "stat": "crit_rate", "value": 2, "target": "self"},
      "effect_chance": 100,
      "max_pp": 15,
    },
    75: {
      "name": "지배의 포효",
      "power": 0,
      "accuracy": 90,
      "type": "dark",
      "category": "status",
      "description": "압도적인 존재감으로 상대를 공포에 질리게 한다.",
      "effect": {"type": "status", "status": "fear", "target": "enemy"},
      "effect_chance": 100,
      "max_pp": 5,
    },
    90: {
      "name": "전투의 정점",
      "power": 0,
      "accuracy": 100,
      "type": "normal",
      "category": "status",
      "description": "수많은 전투 경험으로 모든 능력을 끌어올린다.",
      "effect": [
        {"type": "stat_change", "stat": "strength", "value": 1, "target": "self"},
        {"type": "stat_change", "stat": "defense", "value": 1, "target": "self"},
        {"type": "stat_change", "stat": "agility", "value": 1, "target": "self"},
        {"type": "stat_change", "stat": "intelligence", "value": 1, "target": "self"}
      ],
      "effect_chance": 100,
      "max_pp": 5,
    },
    100: {
      "name": "야수의 왕",
      "power": 150,
      "accuracy": 100,
      "type": "dragon",
      "category": "physical",
      "description": "짐승의 왕으로서 모든 것을 짓밟는다.",
      "effect": [
        {"type": "stat_change", "stat": "strength", "value": 2, "target": "self"},
        {"type": "stat_change", "stat": "defense", "value": -2, "target": "enemy"}
      ],
      "effect_chance": 100,
      "max_pp": 1,
    }
  };
}